// Package hygiene implements the Fleet Console hygiene reports (build
// contract §3.10, phase 15): scheduled report cards answering "what is
// rotting?" — queue inventory, storage attribution, dead-letter digest and
// scheduler health.
//
// Each report is generated by a pure build function over inputs gathered from
// existing substrates (the stats snapshot cache, the §5.8 series rollups, the
// errsig index, scheduler snapshots, Inspector.Servers()) plus BOUNDED direct
// Redis reads (per-report caps documented on the gather functions). Reports
// run on demand (Run now) and on a per-report interval schedule driven by a
// single leased scheduler (asynqmon:lock:hygiene, §5.13 singleton-role
// pattern). Results persist under asynqmon:hygiene:report:<kind> so any
// replica serves the latest report; generation optionally POSTs the report
// JSON to a webhook (best-effort, one attempt, NO retries — v1).
package hygiene

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"strconv"
	"time"

	"github.com/redis/go-redis/v9"
)

// Report kinds (URL slugs — frozen frontend contract, ui/src/api-hygiene.ts).
const (
	KindInventory       = "inventory"
	KindStorage         = "storage"
	KindDeadLetter      = "dead-letter"
	KindSchedulerHealth = "scheduler-health"
)

// Kinds returns every report kind in display order.
func Kinds() []string {
	return []string{KindInventory, KindStorage, KindDeadLetter, KindSchedulerHealth}
}

// Title returns the human title for a kind ("" for unknown kinds).
func Title(kind string) string {
	switch kind {
	case KindInventory:
		return "Queue inventory"
	case KindStorage:
		return "Storage attribution"
	case KindDeadLetter:
		return "Dead-letter digest"
	case KindSchedulerHealth:
		return "Scheduler health"
	}
	return ""
}

// ValidKind reports whether kind names a hygiene report.
func ValidKind(kind string) bool { return Title(kind) != "" }

// ErrStatsUnavailable is returned by report generation when the stats
// snapshot cache is required but absent (stats engine disabled, or no sweep
// has published yet). Handlers translate it into a 503 — never fabricated
// zero-rows.
var ErrStatsUnavailable = errors.New("hygiene: stats snapshot cache unavailable (stats engine disabled or not swept yet)")

// ----------------------------------------------------------------------------
// Report envelope. JSON field names are frozen frontend contracts.
// ----------------------------------------------------------------------------

// Report is one generated hygiene report: the envelope plus exactly one
// kind-specific payload.
type Report struct {
	Kind        string    `json:"kind"`
	GeneratedAt time.Time `json:"generated_at"`
	// DataAsOf stamps the stats snapshot the report was computed from (the
	// honest-numbers rule §2). Nil when the report needed no snapshot
	// (scheduler-health) — a pointer because encoding/json's omitempty never
	// omits a zero time.Time, and the wire contract promises absence.
	DataAsOf *time.Time `json:"data_as_of,omitempty"`
	// Summary carries the card chips: small named counts, kind-specific.
	Summary map[string]int64 `json:"summary"`

	Inventory       *InventoryReport       `json:"inventory,omitempty"`
	Storage         *StorageReport         `json:"storage,omitempty"`
	DeadLetter      *DeadLetterReport      `json:"dead_letter,omitempty"`
	SchedulerHealth *SchedulerHealthReport `json:"scheduler_health,omitempty"`
}

// ----------------------------------------------------------------------------
// Per-report config (asynqmon:hygiene:config HASH, field = kind) + defaults.
// ----------------------------------------------------------------------------

// KindConfig is one report's schedule configuration.
type KindConfig struct {
	Enabled bool `json:"enabled"`
	// IntervalSeconds between scheduled generations.
	IntervalSeconds int64 `json:"interval_seconds"`
}

// Interval config bounds: below a minute the leased scheduler's tick cadence
// makes the interval a lie; beyond 90 days the report store's own TTL would
// expire the previous report first.
const (
	MinIntervalSeconds = 60
	MaxIntervalSeconds = 90 * 24 * 60 * 60
)

// DefaultConfig returns a kind's out-of-the-box schedule: every report starts
// DISABLED (§3.10 empty state: "No reports scheduled — enable the weekly
// inventory to start") with the mockup's cadence as the pre-filled interval.
func DefaultConfig(kind string) KindConfig {
	switch kind {
	case KindInventory:
		return KindConfig{Enabled: false, IntervalSeconds: 7 * 24 * 60 * 60} // weekly
	case KindStorage:
		return KindConfig{Enabled: false, IntervalSeconds: 30 * 24 * 60 * 60} // monthly
	case KindDeadLetter:
		return KindConfig{Enabled: false, IntervalSeconds: 7 * 24 * 60 * 60} // weekly
	case KindSchedulerHealth:
		return KindConfig{Enabled: false, IntervalSeconds: 24 * 60 * 60} // daily
	}
	return KindConfig{}
}

// ValidateConfig checks a config against the interval bounds.
func ValidateConfig(cfg KindConfig) error {
	if cfg.IntervalSeconds < MinIntervalSeconds || cfg.IntervalSeconds > MaxIntervalSeconds {
		return fmt.Errorf("interval_seconds must be between %d (1m) and %d (90d)", MinIntervalSeconds, MaxIntervalSeconds)
	}
	return nil
}

// ----------------------------------------------------------------------------
// Redis keys. asynqmon-owned (never under "asynq:").
// ----------------------------------------------------------------------------

const (
	// configKey is the HASH of per-kind schedule configs (field = kind,
	// value = KindConfig JSON).
	configKey = "asynqmon:hygiene:config"

	// reportKeyPrefix + <kind> is the STRING holding the latest report JSON.
	reportKeyPrefix = "asynqmon:hygiene:report:"

	// lastGenKey is the HASH of per-kind last-generation Unix seconds — the
	// scheduler's cheap due-check without decoding full report bodies.
	lastGenKey = "asynqmon:hygiene:lastgen"

	// lockKey is the singleton lease guarding the hygiene scheduler role
	// (§5.13; same SET NX PX + CAS-renew pattern as the stats sweeper).
	lockKey = "asynqmon:lock:hygiene"

	// reportTTL bounds persisted reports: refreshed on every write, so
	// reports die with a long-dead scheduler instead of serving forever-stale
	// numbers under an honest-looking key.
	reportTTL = 90 * 24 * time.Hour
)

func reportKey(kind string) string { return reportKeyPrefix + kind }

// ----------------------------------------------------------------------------
// Store (engine-independent reads — any replica serves them).
// ----------------------------------------------------------------------------

// ReadConfigs returns every kind's schedule config, defaults merged for kinds
// never configured. Plain Redis reads; before any write the result is simply
// the defaults, never an error.
func ReadConfigs(ctx context.Context, rc redis.UniversalClient) (map[string]KindConfig, error) {
	h, err := rc.HGetAll(ctx, configKey).Result()
	if err != nil && !errors.Is(err, redis.Nil) {
		return nil, err
	}
	out := make(map[string]KindConfig, len(Kinds()))
	for _, kind := range Kinds() {
		cfg := DefaultConfig(kind)
		if raw, ok := h[kind]; ok {
			var stored KindConfig
			if json.Unmarshal([]byte(raw), &stored) == nil && ValidateConfig(stored) == nil {
				cfg = stored
			}
			// Unparsable/out-of-bounds stored values degrade to the default
			// rather than failing the read (written by a future version).
		}
		out[kind] = cfg
	}
	return out, nil
}

// WriteConfig persists one kind's schedule config.
func WriteConfig(ctx context.Context, rc redis.UniversalClient, kind string, cfg KindConfig) error {
	if !ValidKind(kind) {
		return fmt.Errorf("unknown hygiene report kind %q", kind)
	}
	if err := ValidateConfig(cfg); err != nil {
		return err
	}
	raw, err := json.Marshal(cfg)
	if err != nil {
		return err
	}
	return rc.HSet(ctx, configKey, kind, string(raw)).Err()
}

// ReadReport returns the latest persisted report for kind, or nil when none
// was ever generated (or it expired). Decode misses degrade to nil — better a
// missing report than a fabricated one.
func ReadReport(ctx context.Context, rc redis.UniversalClient, kind string) (*Report, error) {
	raw, err := rc.Get(ctx, reportKey(kind)).Bytes()
	if errors.Is(err, redis.Nil) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var rep Report
	if json.Unmarshal(raw, &rep) != nil || rep.Kind == "" {
		return nil, nil
	}
	return &rep, nil
}

// persistReport writes the report body, stamps the last-generation clock and
// refreshes the store TTL.
func persistReport(ctx context.Context, rc redis.UniversalClient, rep *Report) error {
	raw, err := json.Marshal(rep)
	if err != nil {
		return err
	}
	pipe := rc.Pipeline()
	pipe.Set(ctx, reportKey(rep.Kind), raw, reportTTL)
	pipe.HSet(ctx, lastGenKey, rep.Kind, strconv.FormatInt(rep.GeneratedAt.Unix(), 10))
	pipe.PExpire(ctx, lastGenKey, reportTTL)
	_, err = pipe.Exec(ctx)
	return err
}

// readLastGenerated returns each kind's last generation time (absent kinds
// are zero-valued).
func readLastGenerated(ctx context.Context, rc redis.UniversalClient) (map[string]time.Time, error) {
	h, err := rc.HGetAll(ctx, lastGenKey).Result()
	if err != nil && !errors.Is(err, redis.Nil) {
		return nil, err
	}
	out := make(map[string]time.Time, len(h))
	for kind, v := range h {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil && n > 0 {
			out[kind] = time.Unix(n, 0)
		}
	}
	return out, nil
}
