{{- if and .Values.redis.password (not .Values.redis.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-redis" (include "asynqmon.fullname" .) }}
  labels:
    {{- include "asynqmon.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.redis.existingSecretPasswordKey }}: {{ .Values.redis.password | b64enc | quote }}
{{- end }}
